# Generated by Django 5.2.6 on 2025-10-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NiveisDificuldade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nivel', models.CharField(max_length=50, unique=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Nível de Dificuldade',
                'verbose_name_plural': 'Níveis de Dificuldade',
                'db_table': 'niveis_dificuldade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=550, null=True)),
                ('linguas', models.CharField(blank=True, max_length=225, null=True)),
                ('texto', models.CharField(blank=True, max_length=4000, null=True)),
                ('link', models.CharField(blank=True, max_length=550, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'db_table': 'professores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=255)),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('unica', 'Única Escolha'), ('multipla', 'Múltipla Escolha'), ('dissertativa', 'Dissertativa')], default='unica', max_length=12)),
                ('nivel_dificuldade', models.IntegerField()),
                ('microfone', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'db_table': 'questoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('correta', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'db_table': 'respostas',
                'managed': False,
            },
        ),
    ]
