services:
  db:
    image: mysql:8.0
    container_name: mysql_db_local
    env_file:
      - prod.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data_local:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  app:
    build: .
    container_name: django_app_local
    env_file:
      - prod.env
    volumes:
      - static_volume:/app/staticfiles  
    depends_on:
      - db
    restart: always
    entrypoint: /entrypoint.sh 

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy_local
    ports:
      - "8787:8787"
    volumes:
      - static_volume:/app/staticfiles 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
    depends_on:
      - app
    restart: always


volumes:
  mysql_data_local:
  static_volume: